/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Login.Autenticacao;

import DAO.DAOFuncionario;
import View.Init.Principal;
import com.formdev.flatlaf.IntelliJTheme;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lopes
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassowrd = new Source.Classes.Campos.PasswordField();
        txtUsuario = new Source.Classes.Campos.TextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassowrd.setBackground(new java.awt.Color(177, 227, 252));
        txtPassowrd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtPassowrd.setLabelText("Senha");
        txtPassowrd.setShowAndHide(true);
        txtPassowrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassowrdActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassowrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 487, 370, 60));

        txtUsuario.setBackground(new java.awt.Color(177, 227, 252));
        txtUsuario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtUsuario.setLabelText("Usuário");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 400, 370, 60));

        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 575, 260, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/telainicial/tela de cadastro.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassowrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassowrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassowrdActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String usuario, senha;
        usuario = txtUsuario.getText();
        senha = txtPassowrd.getText();
        DAOFuncionario dao = new DAOFuncionario();
        dao.Login(usuario, senha);
        if (dao.conseguiuLogar) {
            this.dispose();
        } else {

        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        IntelliJTheme.setup(Principal.class.getResourceAsStream("/Cyan.theme.json"));

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JToggleButton jToggleButton1;
    private Source.Classes.Campos.PasswordField txtPassowrd;
    private Source.Classes.Campos.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
