/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Init;

import java.awt.Font;
import java.awt.FontFormatException;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Lopes
 */
public class GrupoeSubGrupoInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public GrupoeSubGrupoInternalFrame(javax.swing.JDesktopPane JDesktopPane) {
        initComponents();
        JDesktopPane.add(this);
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException ex) {
            System.out.println("Problema no maximizar");
        }
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setVisible(true);
    }
    
    public Font Pegandoafont() {
        try {
            Font montserrat;
            montserrat = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/Source/Fontes/Montserrat-SemiBold.ttf"));
            montserrat = montserrat.deriveFont(Font.PLAIN, 16);
            return montserrat;
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("deu errado na font");
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CabecalhodoGrupoeSubgrupo = new javax.swing.JLabel();
        SlideMaterialTabbed = new Source.Classes.Slide.MaterialTabbed();
        Painel_Tabela_Grupo = new javax.swing.JPanel();
        PainelBtnGrupo = new javax.swing.JPanel();
        btnNovo1 = new Source.Button.ButtonCommun();
        btnSalvar1 = new Source.Button.ButtonCommun();
        btnRemover1 = new Source.Button.ButtonCommun();
        btnAlterar1 = new Source.Button.ButtonCommun();
        btnCancelar1 = new Source.Button.ButtonCommun();
        Painel_Dados_Subgrupo = new javax.swing.JPanel();
        Componentes = new javax.swing.JPanel();
        PainelBtnSubGrupo = new javax.swing.JPanel();
        btnNovo = new Source.Button.ButtonCommun();
        btnSalvar = new Source.Button.ButtonCommun();
        btnRemover = new Source.Button.ButtonCommun();
        btnAlterar = new Source.Button.ButtonCommun();
        btnCancelar = new Source.Button.ButtonCommun();
        txtNumero = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCEP = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        CadastrodeDadosdoFuncionario = new javax.swing.JLabel();
        BackgroundSlideMaterialTabbed = new javax.swing.JPanel();
        BackgroundCabecalho = new javax.swing.JPanel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMaximumSize(new java.awt.Dimension(1280, 750));
        setMinimumSize(new java.awt.Dimension(5, 5));
        setPreferredSize(new java.awt.Dimension(1280, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CabecalhodoGrupoeSubgrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Img/GrupoeSubGrupo/cabecalho/CabecalhodoGrupoeSubgrupo.png"))); // NOI18N
        CabecalhodoGrupoeSubgrupo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(CabecalhodoGrupoeSubgrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1320, 120));

        SlideMaterialTabbed.setBackground(new java.awt.Color(228, 223, 223));
        SlideMaterialTabbed.setToolTipText("");
        SlideMaterialTabbed.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SlideMaterialTabbed.setMaximumSize(new java.awt.Dimension(1280, 620));
        SlideMaterialTabbed.setMinimumSize(new java.awt.Dimension(1280, 620));
        SlideMaterialTabbed.setPreferredSize(new java.awt.Dimension(1280, 620));

        Painel_Tabela_Grupo.setBackground(new java.awt.Color(228, 223, 223));
        Painel_Tabela_Grupo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelBtnGrupo.setBackground(new java.awt.Color(228, 223, 223));
        PainelBtnGrupo.setAlignmentX(1.0F);
        PainelBtnGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10);
        flowLayout3.setAlignOnBaseline(true);
        PainelBtnGrupo.setLayout(flowLayout3);

        btnNovo1.setBorder(null);
        btnNovo1.setForeground(new java.awt.Color(62, 156, 241));
        btnNovo1.setText("Novo");
        btnNovo1.setColorOver(new java.awt.Color(200, 235, 253));
        btnNovo1.setFocusable(false);
        btnNovo1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnNovo1.setMaximumSize(new java.awt.Dimension(183, 51));
        btnNovo1.setMinimumSize(new java.awt.Dimension(183, 51));
        btnNovo1.setPreferredSize(new java.awt.Dimension(183, 51));
        btnNovo1.setRadius(60);
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo1ActionPerformed(evt);
            }
        });
        PainelBtnGrupo.add(btnNovo1);

        btnSalvar1.setBorder(null);
        btnSalvar1.setForeground(new java.awt.Color(62, 156, 241));
        btnSalvar1.setText("Salvar");
        btnSalvar1.setColorOver(new java.awt.Color(200, 235, 253));
        btnSalvar1.setFocusable(false);
        btnSalvar1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnSalvar1.setMaximumSize(new java.awt.Dimension(183, 51));
        btnSalvar1.setMinimumSize(new java.awt.Dimension(183, 51));
        btnSalvar1.setPreferredSize(new java.awt.Dimension(183, 51));
        btnSalvar1.setRadius(60);
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });
        PainelBtnGrupo.add(btnSalvar1);

        btnRemover1.setBorder(null);
        btnRemover1.setForeground(new java.awt.Color(62, 156, 241));
        btnRemover1.setText("Remover");
        btnRemover1.setColorOver(new java.awt.Color(200, 235, 253));
        btnRemover1.setFocusable(false);
        btnRemover1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnRemover1.setHideActionText(true);
        btnRemover1.setMargin(new java.awt.Insets(2, 30, 2, 30));
        btnRemover1.setMaximumSize(new java.awt.Dimension(183, 51));
        btnRemover1.setMinimumSize(new java.awt.Dimension(183, 51));
        btnRemover1.setPreferredSize(new java.awt.Dimension(183, 51));
        btnRemover1.setRadius(60);
        btnRemover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemover1ActionPerformed(evt);
            }
        });
        PainelBtnGrupo.add(btnRemover1);

        btnAlterar1.setBorder(null);
        btnAlterar1.setForeground(new java.awt.Color(62, 156, 241));
        btnAlterar1.setText("Alterar");
        btnAlterar1.setColorOver(new java.awt.Color(200, 235, 253));
        btnAlterar1.setFocusable(false);
        btnAlterar1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnAlterar1.setMaximumSize(new java.awt.Dimension(183, 51));
        btnAlterar1.setMinimumSize(new java.awt.Dimension(183, 51));
        btnAlterar1.setPreferredSize(new java.awt.Dimension(183, 51));
        btnAlterar1.setRadius(60);
        btnAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterar1ActionPerformed(evt);
            }
        });
        PainelBtnGrupo.add(btnAlterar1);

        btnCancelar1.setBorder(null);
        btnCancelar1.setForeground(new java.awt.Color(62, 156, 241));
        btnCancelar1.setText("Cancelar");
        btnCancelar1.setColorOver(new java.awt.Color(200, 235, 253));
        btnCancelar1.setFocusable(false);
        btnCancelar1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnCancelar1.setMaximumSize(new java.awt.Dimension(183, 51));
        btnCancelar1.setMinimumSize(new java.awt.Dimension(183, 51));
        btnCancelar1.setPreferredSize(new java.awt.Dimension(183, 51));
        btnCancelar1.setRadius(60);
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        PainelBtnGrupo.add(btnCancelar1);

        Painel_Tabela_Grupo.add(PainelBtnGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1320, -1));

        SlideMaterialTabbed.addTab("Grupo", Painel_Tabela_Grupo);

        Painel_Dados_Subgrupo.setPreferredSize(new java.awt.Dimension(1280, 540));
        Painel_Dados_Subgrupo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Componentes.setBackground(new java.awt.Color(228, 223, 223));
        Componentes.setPreferredSize(new java.awt.Dimension(1280, 750));
        Componentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelBtnSubGrupo.setBackground(new java.awt.Color(228, 223, 223));
        PainelBtnSubGrupo.setAlignmentX(1.0F);
        PainelBtnSubGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10);
        flowLayout1.setAlignOnBaseline(true);
        PainelBtnSubGrupo.setLayout(flowLayout1);

        btnNovo.setBorder(null);
        btnNovo.setForeground(new java.awt.Color(62, 156, 241));
        btnNovo.setText("Novo");
        btnNovo.setColorOver(new java.awt.Color(200, 235, 253));
        btnNovo.setFocusable(false);
        btnNovo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnNovo.setMaximumSize(new java.awt.Dimension(183, 51));
        btnNovo.setMinimumSize(new java.awt.Dimension(183, 51));
        btnNovo.setPreferredSize(new java.awt.Dimension(183, 51));
        btnNovo.setRadius(60);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        PainelBtnSubGrupo.add(btnNovo);

        btnSalvar.setBorder(null);
        btnSalvar.setForeground(new java.awt.Color(62, 156, 241));
        btnSalvar.setText("Salvar");
        btnSalvar.setColorOver(new java.awt.Color(200, 235, 253));
        btnSalvar.setFocusable(false);
        btnSalvar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnSalvar.setMaximumSize(new java.awt.Dimension(183, 51));
        btnSalvar.setMinimumSize(new java.awt.Dimension(183, 51));
        btnSalvar.setPreferredSize(new java.awt.Dimension(183, 51));
        btnSalvar.setRadius(60);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        PainelBtnSubGrupo.add(btnSalvar);

        btnRemover.setBorder(null);
        btnRemover.setForeground(new java.awt.Color(62, 156, 241));
        btnRemover.setText("Remover");
        btnRemover.setColorOver(new java.awt.Color(200, 235, 253));
        btnRemover.setFocusable(false);
        btnRemover.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnRemover.setHideActionText(true);
        btnRemover.setMargin(new java.awt.Insets(2, 30, 2, 30));
        btnRemover.setMaximumSize(new java.awt.Dimension(183, 51));
        btnRemover.setMinimumSize(new java.awt.Dimension(183, 51));
        btnRemover.setPreferredSize(new java.awt.Dimension(183, 51));
        btnRemover.setRadius(60);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        PainelBtnSubGrupo.add(btnRemover);

        btnAlterar.setBorder(null);
        btnAlterar.setForeground(new java.awt.Color(62, 156, 241));
        btnAlterar.setText("Alterar");
        btnAlterar.setColorOver(new java.awt.Color(200, 235, 253));
        btnAlterar.setFocusable(false);
        btnAlterar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnAlterar.setMaximumSize(new java.awt.Dimension(183, 51));
        btnAlterar.setMinimumSize(new java.awt.Dimension(183, 51));
        btnAlterar.setPreferredSize(new java.awt.Dimension(183, 51));
        btnAlterar.setRadius(60);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        PainelBtnSubGrupo.add(btnAlterar);

        btnCancelar.setBorder(null);
        btnCancelar.setForeground(new java.awt.Color(62, 156, 241));
        btnCancelar.setText("Cancelar");
        btnCancelar.setColorOver(new java.awt.Color(200, 235, 253));
        btnCancelar.setFocusable(false);
        btnCancelar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnCancelar.setMaximumSize(new java.awt.Dimension(183, 51));
        btnCancelar.setMinimumSize(new java.awt.Dimension(183, 51));
        btnCancelar.setPreferredSize(new java.awt.Dimension(183, 51));
        btnCancelar.setRadius(60);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        PainelBtnSubGrupo.add(btnCancelar);

        Componentes.add(PainelBtnSubGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1320, -1));

        txtNumero.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtNumero.setBorder(null);
        txtNumero.setOpaque(false);
        Componentes.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 390, 38));

        txtCidade.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtCidade.setBorder(null);
        txtCidade.setOpaque(false);
        Componentes.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 390, 38));
        txtCidade.getAccessibleContext().setAccessibleName("");

        txtCelular.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtCelular.setBorder(null);
        txtCelular.setOpaque(false);
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        Componentes.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 282, 390, 38));

        txtCEP.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtCEP.setBorder(null);
        txtCEP.setOpaque(false);
        Componentes.add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 339, 390, 38));

        txtNome.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtNome.setBorder(null);
        txtNome.setOpaque(false);
        Componentes.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 390, 38));

        txtId.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtId.setBorder(null);
        txtId.setOpaque(false);
        Componentes.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 52, 390, 38));

        txtRua.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtRua.setBorder(null);
        txtRua.setOpaque(false);
        Componentes.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 397, 390, 38));

        txtBairro.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtBairro.setBorder(null);
        txtBairro.setOpaque(false);
        Componentes.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 390, 38));
        txtBairro.getAccessibleContext().setAccessibleName("");

        txtCPF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtCPF.setBorder(null);
        txtCPF.setOpaque(false);
        Componentes.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 167, 390, 38));

        txtEmail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.setOpaque(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        Componentes.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 224, 390, 38));

        CadastrodeDadosdoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Img/Funcionario/cabecalho/CadastrodeDadosdoFuncionario.png"))); // NOI18N
        Componentes.add(CadastrodeDadosdoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1310, -1));

        Painel_Dados_Subgrupo.add(Componentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 580));

        SlideMaterialTabbed.addTab("SubGrupo", Painel_Dados_Subgrupo);

        getContentPane().add(SlideMaterialTabbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 120, 1340, 730));

        BackgroundSlideMaterialTabbed.setBackground(new java.awt.Color(228, 223, 223));

        javax.swing.GroupLayout BackgroundSlideMaterialTabbedLayout = new javax.swing.GroupLayout(BackgroundSlideMaterialTabbed);
        BackgroundSlideMaterialTabbed.setLayout(BackgroundSlideMaterialTabbedLayout);
        BackgroundSlideMaterialTabbedLayout.setHorizontalGroup(
            BackgroundSlideMaterialTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
        );
        BackgroundSlideMaterialTabbedLayout.setVerticalGroup(
            BackgroundSlideMaterialTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(BackgroundSlideMaterialTabbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1320, 50));

        BackgroundCabecalho.setBackground(new java.awt.Color(236, 236, 236));

        javax.swing.GroupLayout BackgroundCabecalhoLayout = new javax.swing.GroupLayout(BackgroundCabecalho);
        BackgroundCabecalho.setLayout(BackgroundCabecalhoLayout);
        BackgroundCabecalhoLayout.setHorizontalGroup(
            BackgroundCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        BackgroundCabecalhoLayout.setVerticalGroup(
            BackgroundCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(BackgroundCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 110, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovo1ActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void btnRemover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemover1ActionPerformed

    private void btnAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterar1ActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundCabecalho;
    private javax.swing.JPanel BackgroundSlideMaterialTabbed;
    private javax.swing.JLabel CabecalhodoGrupoeSubgrupo;
    private javax.swing.JLabel CadastrodeDadosdoFuncionario;
    private javax.swing.JPanel Componentes;
    private javax.swing.JPanel PainelBtnGrupo;
    private javax.swing.JPanel PainelBtnSubGrupo;
    private javax.swing.JPanel Painel_Dados_Subgrupo;
    private javax.swing.JPanel Painel_Tabela_Grupo;
    private Source.Classes.Slide.MaterialTabbed SlideMaterialTabbed;
    private Source.Button.ButtonCommun btnAlterar;
    private Source.Button.ButtonCommun btnAlterar1;
    private Source.Button.ButtonCommun btnCancelar;
    private Source.Button.ButtonCommun btnCancelar1;
    private Source.Button.ButtonCommun btnNovo;
    private Source.Button.ButtonCommun btnNovo1;
    private Source.Button.ButtonCommun btnRemover;
    private Source.Button.ButtonCommun btnRemover1;
    private Source.Button.ButtonCommun btnSalvar;
    private Source.Button.ButtonCommun btnSalvar1;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
